### ISSUE TITLE
library directories should not be tracked with git

### ISSUE THREAD

**Issue by sillevl** [vives-projectwerk2-2019/bug-controller#1]
the library directories should not be tracked using git. Both `mbed-lorawan-serialization` and `mbed-Simple-LoRaWAN` should be removed (not ignored) by git.

**Comment by JanssensK** [comment]
Voor moment wordt er in 'experiment' getest en is daar die git verwijderd, zelfde geldt voor issue #2 
Eenmaal dat die branch werkt zal het omgezet worden naar branch master.

**Comment by JanssensK** [comment]
solved  the issue and pushed it to master.
